/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "background": "var(--color-background)",
        "surface-card": "var(--color-surface-card)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-high": "var(--color-surface-container-high)",
        "accent-blue": "var(--color-accent-blue)",
        "on-secondary": "var(--color-on-secondary)",
        "primary": "var(--color-primary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface": "var(--color-surface)",
        "surface-panel": "var(--color-surface-panel)",
        "on-error": "var(--color-on-error)",
        "accent-emerald": "var(--color-accent-emerald)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-container": "var(--color-surface-container)",
        "error-container": "var(--color-error-container)",
        "background-warm": "var(--color-background-warm)",
        "inverse-primary": "var(--color-inverse-primary)",
        "accent-purple": "var(--color-accent-purple)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "tertiary": "var(--color-tertiary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary": "var(--color-secondary)",
        "on-surface": "var(--color-on-surface)",
        "on-primary-container": "var(--color-on-primary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "tertiary-container": "var(--color-tertiary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "secondary-container": "var(--color-secondary-container)",
        "on-background": "var(--color-on-background)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-error-container": "var(--color-on-error-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "border-subtle": "var(--color-border-subtle)",
        "outline-variant": "var(--color-outline-variant)",
        "outline": "var(--color-outline)",
        "on-primary": "var(--color-on-primary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-variant": "var(--color-surface-variant)",
        "error": "var(--color-error)",
        "surface-container-low": "var(--color-surface-container-low)"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "32px",
        "section_gap": "140px",
        "padding_card": "24px",
        "unit_base": "8px",
        "container_max": "1280px"
      },
      fontFamily: {
        "label-caps": ["Geist", "sans-serif"],
        "h1-mobile": ["Geist", "sans-serif"],
        "h2": ["Geist", "sans-serif"],
        "h3": ["Geist", "sans-serif"],
        "h1": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "metric": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "h1-mobile": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "h2": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "h3": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h1": ["84px", { "lineHeight": "1.05", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "metric": ["20px", { "lineHeight": "1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
